In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Downloads/Cars93.csv')

In [3]:
df

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [4]:
df.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

In [6]:
#1. How can you filter cars with horsepower greater than 200?
df[['Model','Horsepower']][df['Horsepower']>200]

       Model  Horsepower
4       535i         208
10   Seville         295
18  Corvette         300
27   Stealth         300
29    Vision         214
47       Q45         278
49     SC300         225
51  Town_Car         210
56      RX-7         255
58      300E         217
62  Diamante         202

In [8]:
#2. Filter cars with horsepower less than or equal to 100.
df[['Model','Horsepower']][df['Horsepower']<=100]

      Model  Horsepower
22     Colt          92
23   Shadow          93
24   Spirit         100
26  Dynasty         100
28   Summit          92
30  Festiva          63
32    Tempo          96
38    Metro          55
39    Storm          90
43    Excel          81
45   Scoupe          92
52      323          82
59    Capri         100
61   Mirage          92
71    Laser          92
72   LeMans          74
78       SL          85
79    Justy          73
80   Loyale          90
82    Swift          70
83   Tercel          82
87      Fox          81

In [11]:
#3. How can you extract cars with exactly 4 cylinders?
df[['Model','Cylinders']][df['Cylinders']=='4']

            Model Cylinders
0         Integra         4
4            535i         4
5         Century         4
11       Cavalier         4
12        Corsica         4
14         Lumina         4
20        LeBaron         4
22           Colt         4
23         Shadow         4
24         Spirit         4
26        Dynasty         4
28         Summit         4
30        Festiva         4
31         Escort         4
32          Tempo         4
33        Mustang         4
34          Probe         4
39          Storm         4
40        Prelude         4
41          Civic         4
42         Accord         4
43          Excel         4
44        Elantra         4
45         Scoupe         4
46         Sonata         4
52            323         4
53        Protege         4
54            626         4
57           190E         4
59          Capri         4
61         Mirage         4
63         Sentra         4
64         Altima         4
67        Achieva         4
68  Cutlass_Ciera         4
71          Laser         4
72         LeMans         4
73        Sunbird         4
77            900         4
78             SL         4
80         Loyale         4
81         Legacy         4
83         Tercel         4
84         Celica         4
85          Camry         4
86         Previa         4
87            Fox         4
89         Passat         4
91            240         4

In [13]:
#4. Filter cars with a price higher than $25,000
df[['Model','Price']][df['Price']>25]

          Model  Price
1        Legend   33.9
2            90   29.1
3           100   37.7
4          535i   30.0
8       Riviera   26.3
9       DeVille   34.7
10      Seville   40.1
18     Corvette   38.0
21     Imperial   29.5
27      Stealth   25.8
47          Q45   47.9
48        ES300   28.0
49        SC300   35.2
50  Continental   34.3
51     Town_Car   36.1
56         RX-7   32.5
57         190E   31.9
58         300E   61.9
62     Diamante   26.1
77          900   28.7
92          850   26.7

In [14]:
#5. How can you extract cars with a weight between 3000 and 3500 lbs?
df[['Model','Weight']][(df['Weight']>=3000)&(df['Weight']<=3500)]

           Model  Weight
2             90    3375
3            100    3405
6        LeSabre    3470
8        Riviera    3495
13        Camaro    3240
14        Lumina    3195
18      Corvette    3380
20       LeBaron    3085
26       Dynasty    3080
29        Vision    3490
36        Taurus    3325
42        Accord    3040
64        Altima    3050
66        Maxima    3200
70  Eighty-Eight    3470
74      Firebird    3240
75    Grand_Prix    3450
76    Bonneville    3495
81        Legacy    3085
85         Camry    3030
92           850    3245

In [34]:
#6. How can you extract cars with an MPG.city greater than or equal to 25?
df[['Model','MPG.city']][df['MPG.city']>=25]

       Model  MPG.city
0    Integra        25
11  Cavalier        25
12   Corsica        25
22      Colt        29
28    Summit        29
30   Festiva        31
38     Metro        46
39     Storm        30
41     Civic        42
43     Excel        29
45    Scoupe        26
52       323        29
53   Protege        28
54       626        26
61    Mirage        29
63    Sentra        29
72    LeMans        31
78        SL        28
79     Justy        33
80    Loyale        25
82     Swift        39
83    Tercel        32
84    Celica        25
87       Fox        25

In [16]:
#7. Filter cars with an MPG.highway less than 20.

df[df['MPG.highway']<20]

Empty DataFrame
Columns: [id, Manufacturer, Model, Type, Min.Price, Price, Max.Price, MPG.city, MPG.highway, AirBags, DriveTrain, Cylinders, EngineSize, Horsepower, RPM, Rev.per.mile, Man.trans.avail, Fuel.tank.capacity, Passengers, Length, Wheelbase, Width, Turn.circle, Rear.seat.room, Luggage.room, Weight, Origin, Make]
Index: []

[0 rows x 28 columns]

In [20]:
#8. How can you extract cars that have a 'Type' of 'Sporty' or 'Compact'?
df['Type'][(df['Type']=='Sporty')|(df['Type']=='Compact')]

2     Compact
11    Compact
12    Compact
13     Sporty
18     Sporty
20    Compact
24    Compact
27     Sporty
32    Compact
33     Sporty
34     Sporty
39     Sporty
40     Sporty
42    Compact
45     Sporty
54    Compact
56     Sporty
57    Compact
59     Sporty
64    Compact
67    Compact
71     Sporty
73    Compact
74     Sporty
77    Compact
81    Compact
84     Sporty
89    Compact
90     Sporty
91    Compact
Name: Type, dtype: object

In [21]:
#9. Filter cars that are either 'Domestic' or 'Imported'
df['Origin'][(df['Origin']=='USA')|(df['Origin']=='non USA')]
df['Type'][(df['Type']=='Sporty')|(df['Type']=='Compact')]

5     USA
6     USA
7     USA
8     USA
9     USA
10    USA
11    USA
12    USA
13    USA
14    USA
15    USA
16    USA
17    USA
18    USA
19    USA
20    USA
21    USA
22    USA
23    USA
24    USA
25    USA
26    USA
27    USA
28    USA
29    USA
30    USA
31    USA
32    USA
33    USA
34    USA
35    USA
36    USA
37    USA
50    USA
51    USA
59    USA
60    USA
67    USA
68    USA
69    USA
70    USA
71    USA
72    USA
73    USA
74    USA
75    USA
76    USA
78    USA
Name: Origin, dtype: object

In [22]:
#10. How can you extract cars with NaN values in the 'Rear.seat.room' column?
df[df['Rear.seat.room'].isna()]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
18,19,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17,25,Driver only,...,2,179,96,74,43,NaN,NaN,3380,USA,Chevrolet Corvette
56,57,Mazda,RX-7,Sporty,32.5,32.5,32.5,17,25,Driver only,...,2,169,96,69,37,NaN,NaN,2895,non-USA,Mazda RX-7

In [23]:
#11. Filter cars that have a 'Manufacturer' name starting with the letter 'C'.
df[df['Manufacturer'].str.startswith('C')]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
9,10,Cadillac,DeVille,Large,33.0,34.7,36.3,16,25,Driver only,...,6,206,114,73,43,35.0,18.0,3620,USA,Cadillac DeVille
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver & Passenger,...,5,204,111,74,44,31.0,14.0,3935,USA,Cadillac Seville
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,NaN,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,5,184,103,68,39,26.0,14.0,2785,USA,Chevrolet Corsica
13,14,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver & Passenger,...,4,193,101,74,43,25.0,13.0,3240,USA,Chevrolet Camaro
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
15,16,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18,23,NaN,...,7,178,110,74,44,30.5,NaN,3715,USA,Chevrolet Lumina_APV
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,NaN,...,8,194,111,78,42,33.5,NaN,4025,USA,Chevrolet Astro
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
18,19,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17,25,Driver only,...,2,179,96,74,43,NaN,NaN,3380,USA,Chevrolet Corvette
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver & Passenger,...,6,183,104,68,41,30.5,14.0,3085,USA,Chrysler LeBaron
21,22,Chrysler,Imperial,Large,29.5,29.5,29.5,20,26,NaN,...,6,203,110,69,44,36.0,17.0,3570,USA,Chrysler Imperial

In [24]:
#12. How can you extract cars with 'AirBags' labeled as 'Non
len(df[df['AirBags']=='None'])

0

In [5]:
#13. Filter cars with 'Man.trans.avail' set to 'Yes'.
df[df['Man.trans.avail']=='Yes']

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [8]:
#14. Filter cars that have a 'Turn.circle' less than 35.
df[df['Turn.circle']<35]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,NaN,...,5,174,98,66,32,26.5,11.0,2270,USA,Dodge Colt
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,NaN,...,4,141,90,63,33,26.0,12.0,1845,USA,Ford Festiva
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,NaN,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,NaN,...,4,166,94,64,34,23.5,9.0,2285,non-USA,Hyundai Scoupe
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,NaN,...,4,164,97,66,34,27.0,16.0,2325,non-USA,Mazda 323
57,58,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,20,29,Driver only,...,5,175,105,67,34,26.0,12.0,2920,non-USA,Mercedes-Benz 190E
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,5,170,96,66,33,26.0,12.0,2545,non-USA,Nissan Sentra
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,NaN,...,4,146,90,60,32,23.5,10.0,2045,non-USA,Subaru Justy
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,NaN,...,4,161,93,63,34,27.5,10.0,1965,non-USA,Suzuki Swift
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,NaN,...,4,163,93,63,34,26.0,10.0,2240,non-USA,Volkswagen Fox

In [9]:
#15. How can you extract cars that have 'Rev.per.mile' greater than 240?
df[df['Rev.per.mile']>240]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [10]:
#16. Filter cars that have 'MPG.city' and 'MPG.highway' values greater than 20.
df[(df['MPG.city']>20)&(df['MPG.highway']>20)]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
5,6,Buick,Century,Midsize,14.2,15.7,17.3,22,31,Driver only,...,6,189,105,69,41,28.0,16.0,2880,USA,Buick Century
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,NaN,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,5,184,103,68,39,26.0,14.0,2785,USA,Chevrolet Corsica
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver & Passenger,...,6,183,104,68,41,30.5,14.0,3085,USA,Chrysler LeBaron
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,NaN,...,5,174,98,66,32,26.5,11.0,2270,USA,Dodge Colt
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,5,172,97,67,38,26.5,13.0,2670,USA,Dodge Shadow
24,25,Dodge,Spirit,Compact,11.9,13.3,14.7,22,27,Driver only,...,6,181,104,68,39,30.5,14.0,2970,USA,Dodge Spirit
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,...,6,192,105,69,42,30.5,16.0,3080,USA,Dodge Dynasty
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,NaN,...,5,174,98,66,36,26.5,11.0,2295,USA,Eagle Summit
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,NaN,...,4,141,90,63,33,26.0,12.0,1845,USA,Ford Festiva
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,NaN,...,5,171,98,67,36,28.0,12.0,2530,USA,Ford Escort
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,NaN,...,5,177,100,68,39,27.5,13.0,2690,USA,Ford Tempo
33,34,Ford,Mustang,Sporty,10.8,15.9,21.0,22,29,Driver only,...,4,180,101,68,40,24.0,12.0,2850,USA,Ford Mustang
34,35,Ford,Probe,Sporty,12.8,14.0,15.2,24,30,Driver only,...,4,179,103,70,38,23.0,18.0,2710,USA,Ford Probe
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,NaN,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,4,164,97,67,37,24.5,11.0,2475,non-USA,Geo Storm
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver & Passenger,...,4,175,100,70,39,23.5,8.0,2865,non-USA,Honda Prelude
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,4,173,103,67,36,28.0,12.0,2350,non-USA,Honda Civic
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver & Passenger,...,4,185,107,67,41,28.0,14.0,3040,non-USA,Honda Accord
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,NaN,...,5,168,94,63,35,26.0,11.0,2345,non-USA,Hyundai Excel
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,22,29,NaN,...,5,172,98,66,36,28.0,12.0,2620,non-USA,Hyundai Elantra
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,NaN,...,4,166,94,64,34,23.5,9.0,2285,non-USA,Hyundai Scoupe
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,NaN,...,4,164,97,66,34,27.0,16.0,2325,non-USA,Mazda 323
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,NaN,...,5,172,98,66,36,26.5,13.0,2440,non-USA,Mazda Protege
54,55,Mazda,626,Compact,14.3,16.5,18.7,26,34,Driver only,...,5,184,103,69,40,29.5,14.0,2970,non-USA,Mazda 626
59,60,Mercury,Capri,Sporty,13.3,14.1,15.0,23,26,Driver only,...,4,166,95,65,36,19.0,6.0,2450,USA,Mercury Capri
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,NaN,...,5,172,98,67,36,26.0,11.0,2295,non-USA,Mitsubishi Mirage
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,5,170,96,66,33,26.0,12.0,2545,non-USA,Nissan Sentra
64,65,Nissan,Altima,Compact,13.0,15.7,18.3,24,30,Driver only,...,5,181,103,67,40,28.5,14.0,3050,non-USA,Nissan Altima
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,28.5,14.0,3200,non-USA,Nissan Maxima
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,NaN,...,5,188,103,67,39,28.0,14.0,2910,USA,Oldsmobile Achieva
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,5,190,105,70,42,28.0,16.0,2890,USA,Oldsmobile Cutlass_Ciera
71,72,Plymouth,Laser,Sporty,11.4,14.4,17.4,23,30,NaN,...,4,173,97,67,39,24.5,8.0,2640,USA,Plymouth Laser
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,NaN,...,4,177,99,66,35,25.5,17.0,2350,USA,Pontiac LeMans
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,NaN,...,5,181,101,66,39,25.0,13.0,2575,USA,Pontiac Sunbird
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,5,176,102,68,40,26.5,12.0,2495,USA,Saturn SL
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,NaN,...,4,146,90,60,32,23.5,10.0,2045,non-USA,Subaru Justy
80,81,Subaru,Loyale,Small,10.5,10.9,11.3,25,30,NaN,...,5,175,97,65,35,27.5,15.0,2490,non-USA,Subaru Loyale
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,27.0,14.0,3085,non-USA,Subaru Legacy
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,NaN,...,4,161,93,63,34,27.5,10.0,1965,non-USA,Suzuki Swift
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,5,162,94,65,36,24.0,11.0,2055,non-USA,Toyota Tercel
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,4,174,99,69,39,23.0,13.0,2950,non-USA,Toyota Celica
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,28.5,15.0,3030,non-USA,Toyota Camry
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,NaN,...,4,163,93,63,34,26.0,10.0,2240,non-USA,Volkswagen Fox
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240

In [25]:
#17. How can you extract cars with a 'Fuel.tank.capacity' less than or equal to 15 gallons?
df[df['Fuel.tank.capacity']<=15]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,NaN,...,5,174,98,66,32,26.5,11.0,2270,USA,Dodge Colt
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,5,172,97,67,38,26.5,13.0,2670,USA,Dodge Shadow
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,NaN,...,5,174,98,66,36,26.5,11.0,2295,USA,Eagle Summit
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,NaN,...,4,141,90,63,33,26.0,12.0,1845,USA,Ford Festiva
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,NaN,...,5,171,98,67,36,28.0,12.0,2530,USA,Ford Escort
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,NaN,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro
39,40,Geo,Storm,Sporty,11.5,12.5,13.5,30,36,Driver only,...,4,164,97,67,37,24.5,11.0,2475,non-USA,Geo Storm
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,4,173,103,67,36,28.0,12.0,2350,non-USA,Honda Civic
43,44,Hyundai,Excel,Small,6.8,8.0,9.2,29,33,NaN,...,5,168,94,63,35,26.0,11.0,2345,non-USA,Hyundai Excel
44,45,Hyundai,Elantra,Small,9.0,10.0,11.0,22,29,NaN,...,5,172,98,66,36,28.0,12.0,2620,non-USA,Hyundai Elantra
45,46,Hyundai,Scoupe,Sporty,9.1,10.0,11.0,26,34,NaN,...,4,166,94,64,34,23.5,9.0,2285,non-USA,Hyundai Scoupe
52,53,Mazda,323,Small,7.4,8.3,9.1,29,37,NaN,...,4,164,97,66,34,27.0,16.0,2325,non-USA,Mazda 323
53,54,Mazda,Protege,Small,10.9,11.6,12.3,28,36,NaN,...,5,172,98,66,36,26.5,13.0,2440,non-USA,Mazda Protege
57,58,Mercedes-Benz,190E,Compact,29.0,31.9,34.9,20,29,Driver only,...,5,175,105,67,34,26.0,12.0,2920,non-USA,Mercedes-Benz 190E
59,60,Mercury,Capri,Sporty,13.3,14.1,15.0,23,26,Driver only,...,4,166,95,65,36,19.0,6.0,2450,USA,Mercury Capri
61,62,Mitsubishi,Mirage,Small,7.7,10.3,12.9,29,33,NaN,...,5,172,98,67,36,26.0,11.0,2295,non-USA,Mitsubishi Mirage
63,64,Nissan,Sentra,Small,8.7,11.8,14.9,29,33,Driver only,...,5,170,96,66,33,26.0,12.0,2545,non-USA,Nissan Sentra
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,NaN,...,4,177,99,66,35,25.5,17.0,2350,USA,Pontiac LeMans
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,5,176,102,68,40,26.5,12.0,2495,USA,Saturn SL
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,NaN,...,4,146,90,60,32,23.5,10.0,2045,non-USA,Subaru Justy
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,NaN,...,4,161,93,63,34,27.5,10.0,1965,non-USA,Suzuki Swift
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,5,162,94,65,36,24.0,11.0,2055,non-USA,Toyota Tercel
87,88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,NaN,...,4,163,93,63,34,26.0,10.0,2240,non-USA,Volkswagen Fox

In [12]:
#18. Filter cars with a 'Length' greater than 190 inches
df[df['Length']>190]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
8,9,Buick,Riviera,Midsize,26.3,26.3,26.3,19,27,Driver only,...,5,198,108,73,41,26.5,14.0,3495,USA,Buick Riviera
9,10,Cadillac,DeVille,Large,33.0,34.7,36.3,16,25,Driver only,...,6,206,114,73,43,35.0,18.0,3620,USA,Cadillac DeVille
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver & Passenger,...,5,204,111,74,44,31.0,14.0,3935,USA,Cadillac Seville
13,14,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver & Passenger,...,4,193,101,74,43,25.0,13.0,3240,USA,Chevrolet Camaro
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,NaN,...,8,194,111,78,42,33.5,NaN,4025,USA,Chevrolet Astro
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
21,22,Chrysler,Imperial,Large,29.5,29.5,29.5,20,26,NaN,...,6,203,110,69,44,36.0,17.0,3570,USA,Chrysler Imperial
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,...,6,192,105,69,42,30.5,16.0,3080,USA,Dodge Dynasty
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
47,48,Infiniti,Q45,Midsize,45.4,47.9,50.4,17,22,Driver only,...,5,200,113,72,42,29.0,15.0,4000,non-USA,Infiniti Q45
49,50,Lexus,SC300,Midsize,34.7,35.2,35.6,18,23,Driver & Passenger,...,4,191,106,71,39,25.0,9.0,3515,non-USA,Lexus SC300
50,51,Lincoln,Continental,Midsize,33.3,34.3,35.3,17,26,Driver & Passenger,...,6,205,109,73,42,30.0,19.0,3695,USA,Lincoln Continental
51,52,Lincoln,Town_Car,Large,34.4,36.1,37.8,18,26,NaN,...,6,219,117,77,45,31.5,22.0,4055,USA,Lincoln Town_Car
60,61,Mercury,Cougar,Midsize,14.9,14.9,14.9,19,26,NaN,...,5,199,113,73,38,28.0,15.0,3610,USA,Mercury Cougar
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,NaN,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,NaN,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix